// Drizzle table definitions; drizzle-kit diffs this file to generate migrations.
// Auth tables are generated by `npm run auth:generate` (see tech-docs/auth.md); todos arrive with the architecture.
export * from "./auth-schema";
