// Drizzle table definitions; drizzle-kit diffs this file to generate migrations.
// Auth tables are generated by `npm run auth:generate` (see tech-docs/auth.md).
import { sql } from "drizzle-orm";
import {
  check,
  index,
  integer,
  sqliteTable,
  text,
} from "drizzle-orm/sqlite-core";
import { user } from "./auth-schema";

export * from "./auth-schema";

// Only lib/todo-service.ts reads or writes this table (see tech-docs/architecture.md).
export const todos = sqliteTable(
  "todos",
  {
    id: text("id").primaryKey(),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    // A calendar date as `yyyy-mm-dd` text, never a timestamp.
    dueDate: text("due_date"),
    done: integer("done", { mode: "boolean" }).default(false).notNull(),
    createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull(),
    completedAt: integer("completed_at", { mode: "timestamp_ms" }),
  },
  (table) => [
    index("todos_userId_idx").on(table.userId),
    // A done todo always has a completion time, and an open one never does.
    check(
      "todos_completed_at_matches_done",
      sql`(${table.done} = 1) = (${table.completedAt} is not null)`,
    ),
  ],
);
